version: '3.8'

services:
  app:
    container_name: template-server
    build: .
    volumes:
      - ./logs:/app/logs # 호스트의 logs 폴더를 컨테이너의 /app/logs에 마운트
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=dev
