version: '3.8'

networks:
  opensearch-network:
    driver: bridge

services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - "discovery.type=single-node"
      - "plugins.security.disabled=true"  # ✅ 보안 비활성화 (로그인 없이 사용 가능)
      - "DISABLE_INSTALL_DEMO_CONFIG=true"  # ✅ 데모 설정 제거
      - "DISABLE_SECURITY_PLUGIN=true"  # ✅ 보안 플러그인 비활성화
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - opensearch-network

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    environment:
      - "OPENSEARCH_HOSTS=http://opensearch:9200"  # ✅ 인증 없이 OpenSearch에 연결
    ports:
      - "5601:5601"
    depends_on:
      - opensearch
    networks:
      - opensearch-network

  fluentd:
    build:
      context: ./fluentd
      dockerfile: Dockerfile
    container_name: fluentd
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - ./logs:/var/log/app
    depends_on:
      - opensearch
    networks:
      - opensearch-network

  nestjs-app:
    container_name: nestjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - opensearch
      - fluentd
    networks:
      - opensearch-network